name: sm_ms
description: Graph bed from [https://sm.ms/]
version: 0.3.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_imagenetwork: ^0.6.1
  ajanuw_http: ^0.3.0

  mobx: ^1.2.1+3
  flutter_mobx: ^1.1.0+2
  shared_preferences: '>=0.5.12 <2.0.0'
  path:
  image_picker: ^0.6.7+11

  built_value:
  built_collection:
  toast: ^0.1.5
  url_launcher: ^5.7.2
  get_it: ^5.0.1
  dart_printf:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  mobx_codegen:
  built_value_generator:

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
